# Generated by Django 5.0 on 2023-12-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptpud04', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motoelectrica',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
